// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainerManager.Infrastructure.Data;

#nullable disable

namespace TrainerManager.Infrastructure.Migrations
{
    [DbContext(typeof(TrainerDbContext))]
    partial class TrainerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("TrainerManager.Domain.Entities.ClientTrainingHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientCompanyName")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationInDays")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TechnologyTaught")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TrainerId");

                    b.ToTable("TrainingHistories");
                });

            modelBuilder.Entity("TrainerManager.Domain.Entities.Trainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AlternateEmail")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlternateMobileNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Field")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdentityNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastCompanyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedInUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResumePath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Specialization")
                        .HasColumnType("TEXT");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Trainers");
                });

            modelBuilder.Entity("TrainerManager.Domain.Entities.ClientTrainingHistory", b =>
                {
                    b.HasOne("TrainerManager.Domain.Entities.Trainer", null)
                        .WithMany("TrainingHistory")
                        .HasForeignKey("TrainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TrainerManager.Domain.Entities.Trainer", b =>
                {
                    b.OwnsOne("TrainerManager.Domain.Entities.TrainerAccount", "AccountDetails", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("AccountNumber")
                                .HasColumnType("TEXT");

                            b1.Property<string>("BankName")
                                .HasColumnType("TEXT");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.OwnsOne("TrainerManager.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.OwnsMany("TrainerManager.Domain.ValueObjects.TrainerCertification", "Certifications", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<string>("CertificateUrl")
                                .HasColumnType("TEXT");

                            b1.Property<DateTime>("DateObtained")
                                .HasColumnType("TEXT");

                            b1.Property<string>("IssuingOrganization")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .HasColumnType("TEXT");

                            b1.Property<int>("TrainerId")
                                .HasColumnType("INTEGER");

                            b1.HasKey("Id");

                            b1.HasIndex("TrainerId");

                            b1.ToTable("TrainerCertifications", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.OwnsOne("TrainerManager.Domain.ValueObjects.TrainerCosting", "Costing", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<decimal>("HourlyRate")
                                .HasColumnType("TEXT");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.OwnsOne("TrainerManager.Domain.ValueObjects.VisaDetails", "Visa", b1 =>
                        {
                            b1.Property<int>("TrainerId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Country")
                                .HasColumnType("TEXT")
                                .HasColumnName("VisaCountry");

                            b1.Property<DateTime?>("ExpiryDate")
                                .HasColumnType("TEXT")
                                .HasColumnName("VisaExpiryDate");

                            b1.Property<int>("Id")
                                .HasColumnType("INTEGER");

                            b1.Property<bool>("IsWorkAuthorized")
                                .HasColumnType("INTEGER")
                                .HasColumnName("VisaIsWorkAuthorized");

                            b1.Property<string>("VisaType")
                                .HasColumnType("TEXT")
                                .HasColumnName("VisaType");

                            b1.HasKey("TrainerId");

                            b1.ToTable("Trainers");

                            b1.WithOwner()
                                .HasForeignKey("TrainerId");
                        });

                    b.Navigation("AccountDetails")
                        .IsRequired();

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("Certifications");

                    b.Navigation("Costing")
                        .IsRequired();

                    b.Navigation("Visa")
                        .IsRequired();
                });

            modelBuilder.Entity("TrainerManager.Domain.Entities.Trainer", b =>
                {
                    b.Navigation("TrainingHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
